#!/usr/bin/env python3
# pylint: disable=invalid-name

"""
Git pre-commit hook for checking Python code quality. The hook requires pylint
to check the code quality.

AUTHOR:
    Sebastian Dahlgren <sebastian.dahlgren@gmail.com>

VERSION:
    0.8

LICENSE:
    Apache License 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html
"""

import os
import re
import sys
import subprocess

#######################################
#
# CONFIGURATION
#
#######################################

# The lowest allowed score (should be a float between 0.00 and 10.00)
LIMIT = 8.0

# Custom pylint command line parameters. See pylint --help for more info
# E.g.
# PYLINT_PARAMS = '--rcfile=/path/to/project/pylint.rc'
PYLINT_PARAMS = ''

#######################################
#
# CODE BELOW
#
#######################################


def get_list_of_committed_files():
    """
    Returns a list of files about to be commited.
    """
    files = []
    # pylint: disable=E1103
    output = subprocess.check_output(
        'git diff-index --cached HEAD'.split(), text=True)
    for result in output.split('\n'):
        if result != '':
            result = result.split()
            if result[4] in ['A', 'M']:
                files.append(result[5])

    return files


def checker():  # pylint: disable=too-many-branches,too-many-locals
    """
    Main function doing the checks
    """
    # List of checked files and their results
    python_files = []

    # Set the exit code
    exit_code = 0

    # Find Python files
    for filename in get_list_of_committed_files():
        # Check the file extension
        if filename[-3:] == '.py':
            python_files.append((filename, None))
            continue

        # Check the first line for a python shebang
        try:
            with open(filename, 'r', encoding='utf-8') as file_handle:
                first_line = file_handle.readline()
            if 'python' in first_line and '#!' in first_line:
                python_files.append((filename, None))
        except IOError:
            print(f'File not found (probably deleted): {filename}\t\tSKIPPED')

    # Don't do anything if there are no Python files
    if len(python_files) == 0:
        sys.exit(0)

    # Pylint Python files
    i = 1
    regexp = re.compile(r'^Your\ code\ has\ been\ rated\ at\ (\-?[0-9\.]+)/10')
    for python_file, score in python_files:
        # Allow __init__.py files to be completely empty
        if os.path.basename(python_file) == '__init__.py':
            if os.stat(python_file).st_size == 0:
                print(f'Skipping pylint on {python_file} (empty __init__.py)..\tSKIPPED')

                # Bump parsed files
                i += 1
                continue

        # Set the initial score
        score = 0.00

        # Start pylinting
        msg = f"Running pylint on {python_file} (file {i}/{len(python_files)})..\t"
        sys.stdout.write(msg)
        sys.stdout.flush()
        try:
            if PYLINT_PARAMS:
                command = f'.virtualenv/bin/pylint {PYLINT_PARAMS} {python_file}'
            else:
                command = f'.virtualenv/bin/pylint {python_file}'
            with subprocess.Popen(
                command.split(),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True) as proc:
                out, _ = proc.communicate()
        except OSError:
            print("\nAn error occurred. Is pylint installed?")
            sys.exit(1)

        # Check for the result
        # pylint: disable=E1103
        for line in out.split('\n'):
            match = re.match(regexp, line)
            if match:
                score = float(match.group(1))

        # Verify the score
        if score >= float(LIMIT):
            status = 'PASSED'
        else:
            status = 'FAILED'
            exit_code = 1

        # Add some output
        print(f'{score:.2f}/10.00\t{status}')

        # Bump parsed files
        i += 1

    sys.exit(exit_code)

if __name__ == '__main__':
    checker()

sys.exit(1)
